ekfMap_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 10.0
    two_d_mode: true
    transform_time_offset: 0.1

    predict_to_current_time: true
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    debug_out_file: ekf.log

    publish_tf: true

    publish_acceleration: false

    map_frame: map
    odom_frame: odom            
    base_link_frame: base_link  
    world_frame: map
    # x, y, z,
    # roll, pitch, yaw,
    # vx, vy, vz,
    # vroll, vpitch, vyaw,
    # ax, ay, az
    odom0: /odometry/gps

    odom0_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false

    odom1: /antobot_lidar_odom/Odometry

    odom1_config: [ true, true,  false,
                    false, false, true,
                    true, true, false,
                    false, false, true,
                    false, false, false ]

    odom1_queue_size: 10
    odom1_nodelay: true
    odom1_differential: true
    odom1_relative: false

    # Further input parameter
    imu0: /imu/data_corrected
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    imu0_nodelay: true
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 5
    imu0_remove_gravitational_acceleration: true # false for Bosch IMU

    use_control: false
    stamped_control: false
    control_timeout: 0.2
    control_config: [true, false, false, false, false, true]
    acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.4]
    deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 4.5]
    acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
    deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    dynamic_process_noise_covariance: true

    process_noise_covariance: [0.0002,  0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0002, 0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.00048,  0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.00015,  0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.00015,  0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.00003,  0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.00025,  0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.00025,  0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0004,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.01,   0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.01,   0.0,    0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.02,   0.0,    0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.01,   0.0,    0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.01,   0.0,
                               0.0,     0.0,    0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,      0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
    
    
    initial_estimate_covariance: [1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    1e-2,   0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    
                                  0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-2,   0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-2,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     1e-2,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    1e-2,   0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    1e-2,   0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9]


