navsat_transform_node:
  ros__parameters:
    frequency: 30.0 
    delay: 3.0
    magnetic_declination_radians: 0 
    yaw_offset: 0 
    zero_altitude: false
    broadcast_utm_transform: true
    broadcast_utm_transform_as_parent_frame: false
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false


